# -*- coding: utf-8 -*-
"""Contact List Scraping Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUGmbdkPAiQwtSDk-fM6i9ebDj0CUPw4
"""



"""```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Google Places Scraper</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { padding-top: 20px; }
        .container { max-width: 900px; }
        textarea { resize: vertical; }
    </style>
</head>
<body>
    <div class="container">
        <h1 class="mb-4">Google Places Contact Scraper (Flask)</h1>

        {% if error_message %}
            <div class="alert alert-danger" role="alert">
                {{ error_message }}
            </div>
        {% endif %}

        <form method="POST" action="/">
            <div class="form-group">
                <label for="api_key">Google Cloud API Key:</label>
                <input type="password" class="form-control" id="api_key" name="api_key" required>
                <small class="form-text text-muted">Your API key (Places API, Geocoding API).</small>
            </div>

            <div class="form-group">
                <label for="target_cities">Target Cities & States:</label>
                <textarea class="form-control" id="target_cities" name="target_cities" rows="3" required>{{ default_cities }}</textarea>
                <small class="form-text text-muted">Enter one city and state per line (e.g., 'Panama City, FL').</small>
            </div>

            <div class="form-group">
                <label for="search_radius_miles">Search Radius (Miles):</label>
                <input type="number" class="form-control" id="search_radius_miles" name="search_radius_miles" value="{{ default_radius }}" min="1" max="100" step="1" required>
                <small class="form-text text-muted">The radius around each city to search for businesses.</small>
            </div>

            <div class="form-group">
                <label for="business_types">Business Types:</label>
                <textarea class="form-control" id="business_types" name="business_types" rows="3" required>{{ default_business_types }}</textarea>
                <small class="form-text text-muted">Enter one business type per line (e.g., 'property manager', 'realtor', 'apartment').</small>
            </div>

            <button type="submit" class="btn btn-primary btn-lg btn-block">Run Scraper</button>
        </form>

        {% if df_html %}
            <h2 class="mt-5">Results (First 10 Prioritized Contacts):</h2>
            {{ df_html | safe }}
            <div class="text-center mt-4">
                {{ download_link | safe }}
            </div>
        {% endif %}

    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>
```
"""